//
//  SOHookSettingController.h
//  SoulHook
//
//  Created by 月成 on 2019/6/25.
//  Copyright © 2019 fancy. All rights reserved.
//

#import <UIKit/UIKit.h>

#define SOUL_HOOK_FINGER_TYPE             @"SOUL_HOOK_FINGER_TYPE"
#define SOUL_HOOK_DICE_TYPE               @"SOUL_HOOK_DICE_TYPE"
#define SOUL_HOOK_FINGER_SWITCH           @"SOUL_HOOK_FINGER_SWITCH"
#define SOUL_HOOK_DICE_SWITCH             @"SOUL_HOOK_DICE_SWITCH"
#define SOUL_HOOK_MSG_REVOKE_SWITCH       @"SOUL_HOOK_MSG_REVOKE_SWITCH"
#define SOUL_HOOK_MSG_FLASH_SWITCH        @"SOUL_HOOK_MSG_FLASH_SWITCH"
#define SOUL_HOOK_MSG_COPY_SWITCH         @"SOUL_HOOK_MSG_COPY_SWITCH"
#define SOUL_HOOK_AVATAR_SWITCH           @"SOUL_HOOK_AVATAR_SWITCH"
#define SOUL_HOOK_AVATAR_BG_SWITCH        @"SOUL_HOOK_AVATAR_BG_SWITCH"
#define SOUL_HOOK_AVATAR_CUSTOM_SWITCH    @"SOUL_HOOK_AVATAR_CUSTOM_SWITCH"
#define SOUL_HOOK_SOULMATE_SWITCH         @"SOUL_HOOK_SOULMATE_SWITCH"
#define SOUL_HOOK_ADVERT_SWITCH           @"SOUL_HOOK_ADVERT_SWITCH"
#define SOUL_HOOK_LOCATION_SWITCH         @"SOUL_HOOK_LOCATION_SWITCH"
#define SOUL_HOOK_BIRTHDAY_GENDER_SWITCH  @"SOUL_HOOK_BIRTHDAY_GENDER_SWITCH"
#define SOUL_HOOK_POST_VISIBILITY_SWITCH  @"SOUL_HOOK_POST_VISIBILITY_SWITCH"
#define SOUL_HOOK_READ_SWITCH             @"SOUL_HOOK_READ_SWITCH"
#define SOUL_HOOK_INPUT_STATE_SWITCH      @"SOUL_HOOK_INPUT_STATE_SWITCH"
#define SOUL_HOOK_MSG_RECALL_SWITCH       @"SOUL_HOOK_MSG_RECALL_SWITCH"
#define SOUL_HOOK_WATER_MARK_SWITCH       @"SOUL_HOOK_WATER_MARK_SWITCH"
#define SOUL_HOOK_AUTO_REPLY_ALL_SWITCH   @"SOUL_HOOK_AUTO_REPLY_ALL_SWITCH"
#define SOUL_HOOK_AUTO_REPLY_KEY_SWITCH   @"SOUL_HOOK_AUTO_REPLY_KEY_SWITCH"
#define SOUL_HOOK_AUTO_READ_KEY_SWITCH    @"SOUL_HOOK_AUTO_READ_KEY_SWITCH"
#define SOUL_HOOK_ROBOT_SWITCH            @"SOUL_HOOK_ROBOT_SWITCH"

#define SOUL_HOOK_AUTO_REPLY_KEYS         @"SOUL_HOOK_AUTO_REPLY_KEYS"
#define SOUL_HOOK_AUTO_REPLY_TEXTS        @"SOUL_HOOK_AUTO_REPLY_TEXTS"
#define SOUL_HOOK_MATCH_VALUE             @"SOUL_HOOK_MATCH_VALUE"
#define SOUL_HOOK_WHITE_LIST              @"SOUL_HOOK_WHITE_LIST"

NS_ASSUME_NONNULL_BEGIN

@interface SOHookSettingController : UIViewController

@end

NS_ASSUME_NONNULL_END
